import { groupMock } from '../../lib/mockData';
import type { Currency } from '../../lib/utils';
import { money, percent } from '../../lib/utils';

type Props = { currency: Currency; onContribute: () => void };
export default function GroupScreen({ currency, onContribute }: Props){
  const total = groupMock.members.reduce((s,m)=>s+m.saved,0);
  return <div className="h-full app-scroll overflow-y-auto px-5 pb-28 pt-8 fade-in"><h1 className="text-2xl font-black">Finanzas compartidas</h1><p className="mt-2 text-sm text-[var(--muted)]">Organiza aportes y gastos en equipo sin perder claridad.</p><section className="card mt-5 rounded-[2rem] p-5"><div className="flex items-center justify-between"><div><div className="text-4xl">{groupMock.emoji}</div><h2 className="mt-2 text-xl font-black">{groupMock.name}</h2></div><span className="rounded-2xl soft-btn px-3 py-2 text-xs">Activo</span></div><p className="mt-5 text-sm text-[var(--muted)]">Saldo del grupo</p><strong className="text-3xl">{money(total,currency)}</strong><div className="mt-3 progress"><span style={{width:`${percent(total,groupMock.target)}%`}} /></div><p className="mt-2 text-xs text-[var(--muted)]">Meta compartida: {money(groupMock.target,currency)}</p><button onClick={onContribute} className="tap mt-4 w-full rounded-2xl py-3 font-bold gradient-btn">Registrar aporte</button></section><h2 className="mt-5 font-black">Miembros</h2><div className="mt-3 space-y-3">{groupMock.members.map(m=><div key={m.name} className="card flex items-center justify-between rounded-3xl p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl gradient-btn font-bold">{m.avatar}</span><b>{m.name}</b></div><span>{money(m.saved,currency)}</span></div>)}</div><h2 className="mt-5 font-black">Gastos compartidos</h2><div className="mt-3 space-y-3">{groupMock.expenses.map(e=><div key={e.id} className="card flex justify-between rounded-3xl p-4"><span>{e.name}</span><b>{money(e.amount,currency)}</b></div>)}</div></div>
}
